steps:
  # Paso 1: Construcción de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/alamo-utec/openai_assistant_flask', '.']
    
  # Paso 2: Push de la imagen al registro de contenedores
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/alamo-utec/openai_assistant_flask']
  
  # Paso 3: Ejecutar el trigger de despliegue en Cloud Build
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
        - 'builds'
        - 'triggers'
        - 'run'
        - 'openai-deploy-trigger'
        - '--region=southamerica-east1'

images:
  - 'gcr.io/alamo-utec/openai_assistant_flask'

options:
  logging: CLOUD_LOGGING_ONLY
