steps:
  # Paso 1: Construcción de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/alamo-utec/openai_assistant_flask', '.']
    
  # Paso 2: Push de la imagen al registro de contenedores
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/alamo-utec/openai_assistant_flask']
  
  # Paso 3: Llamada a la API de Cloud Build usando el secreto para el trigger
  - name: 'curlimages/curl'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          "https://cloudbuild.googleapis.com/v1/$DEPLOY_TRIGGER_PATH:run"
    env:
      - 'DEPLOY_TRIGGER_PATH'
    secretEnv: ['DEPLOY_TRIGGER_PATH']

availableSecrets:
  secretManager:
    - versionName: projects/934172637590/secrets/DEPLOY_TRIGGER_PATH
      env: 'DEPLOY_TRIGGER_PATH'

images:
  - 'gcr.io/alamo-utec/openai_assistant_flask'

options:
  logging: CLOUD_LOGGING_ONLY
