steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/alamo-utec/openai_assistant_flask', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/alamo-utec/openai_assistant_flask']

images:
  - 'gcr.io/alamo-utec/openai_assistant_flask'

options:
  logging: CLOUD_LOGGING_ONLY
